### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by oubiwann** [lfex/kanin#13]
Tasks:
 * [x] Create new home for docs - #14
 * [x] Provide high-level overview of APIs in new docs home - #15
 * [x] Move existing README docs into new docs home - #16
 * [x] Add new docs for supervised kanin API - #17

Part of epic #4

**Comment by oubiwann** [comment]
Done.
