### ISSUE TITLE
Convert kanin tutorials to new API

### ISSUE THREAD

**Issue by oubiwann** [lfex/kanin#32]
The tasks for this epic are actually contained in another repository:
 * [ ] Update Ch1 to use the new API - https://github.com/billosys/kanin-tutorials-book/issues/1
 * [ ] Update Ch2 to use the new API  - https://github.com/billosys/kanin-tutorials-book/issues/2
 * [ ] Write Ch3 - https://github.com/billosys/kanin-tutorials-book/issues/3
 * [ ] Write Ch4 - https://github.com/billosys/kanin-tutorials-book/issues/4
 * [ ] Write Ch5 - https://github.com/billosys/kanin-tutorials-book/issues/5
 * [ ] Write Ch6 - https://github.com/billosys/kanin-tutorials-book/issues/6
 * [ ] Write Ch7 - https://github.com/billosys/kanin-tutorials-book/issues/7
 * Tutorial touch-ups and maintenance:
    * [ ] Update to use the latest Gitbook - https://github.com/billosys/kanin-tutorials-book/issues/9
    * [ ] Add Section to README explaining/crediting source  - https://github.com/billosys/kanin-tutorials-book/issues/10
    * [ ] Add SUMMARY/ToC link to README  - https://github.com/billosys/kanin-tutorials-book/issues/11

Part of release [v0.7.0](https://github.com/lfex/kanin/issues/33)
