### ISSUE TITLE
v0.7.0

### ISSUE THREAD

**Issue by oubiwann** [lfex/kanin#33]
This ticket tracks the high-level work (epics) going into the release.

* [ ] Add supervised API - #4
* [ ] Convert kanin tutorials to new API - #32
* [ ] Provide function wrappers for AMQP commands - #35
