### ISSUE TITLE
Provide function wrappers for AMQP commands

### ISSUE THREAD

**Issue by oubiwann** [lfex/kanin#35]
Features and Tasks:

* [ ] Examine kanin-supported AMQP commands to determine wrapper feasibility - #36
* [ ] Prototype a macro capable of providing a good developer experience for kanin AMQP commands - #37
* [ ] Re-assess level of effort for implementing kanin AMQP commands - #38
* [x] Build list of AMQP commands requiring wrapping - #39
* [ ] Implement AMQP command wrappers - #40

Part of release [v0.7.0](https://github.com/lfex/kanin/issues/33)
