### ISSUE TITLE
Provide kanin server for failure+state management

### ISSUE THREAD

**Issue by oubiwann** [lfex/kanin#7]
This should start when the kanin application starts. It will track connection options, a default connection (with the ability to support more, including connection pooling in the future), a default channel (reducing channel-related function arities by one in the default case), and the ability to support more channels in the user desires.

Tasks:

 * [x] Create kanin gen_server modules and populate with base code - #19
 * [x] Create init function that takes network options and initializes state - #20
 * [x] Create gen_server function for making mod:func calls to Erlang RabbitMQ libraries - #21
 * [x] Create special gen_server functions to support high-level API - #22
 * [x] Register application

Branch:
 * [feature/7/kanin-server](https://github.com/lfex/kanin/tree/feature/7/kanin-server)

Part of epic #4

**Comment by oubiwann** [comment]
Done.
