### ISSUE TITLE
Provide a high-level API that uses supervised kanin

### ISSUE THREAD

**Issue by oubiwann** [lfex/kanin#8]
Tasks:

 * [x] Evaluate all includes for conflicting Erlang Client and Rabbit Common libraries - #9
 * [x] Create kanin module for the new API - #10
 * [x] Populate kanin module with multi-arity API functions - #11

Part of epic #4
